import { createServer } from 'node:http';
import { execFile } from 'node:child_process';
import { promisify } from 'node:util';
import { readFile, readdir, writeFile, mkdir, rename, unlink } from 'node:fs/promises';
import { randomBytes, timingSafeEqual } from 'node:crypto';
import { extname, join, normalize, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';
import { adminPassword } from './config.mjs';

const execFileAsync=promisify(execFile),root=fileURLToPath(new URL('.',import.meta.url)),contentPath=join(root,'private','content.json'),docsPath=join(root,'docs'),manifestPath=join(docsPath,'manifest.json'),sessions=new Map(),port=Number(process.env.PORT||8787);
const mime={'.html':'text/html; charset=utf-8','.js':'text/javascript; charset=utf-8','.css':'text/css; charset=utf-8','.json':'application/json; charset=utf-8','.md':'text/markdown; charset=utf-8','.svg':'image/svg+xml','.ico':'image/x-icon'};
const json=(res,code,value)=>{res.writeHead(code,{'Content-Type':'application/json; charset=utf-8','Cache-Control':'no-store'});res.end(JSON.stringify(value))};
const body=req=>new Promise((resolve,reject)=>{let data='';req.on('data',c=>{data+=c;if(data.length>250000)req.destroy()});req.on('end',()=>{try{resolve(JSON.parse(data||'{}'))}catch{reject(new Error('Ungültige Anfrage.'))}})});
const sessionFor=req=>{const id=/(?:^|; )blueprint_session=([^;]+)/.exec(req.headers.cookie||'')?.[1];return id&&sessions.get(id)};
const same=(a,b)=>{const x=Buffer.from(a),y=Buffer.from(b);return x.length===y.length&&timingSafeEqual(x,y)};
const requireAuth=(req,res)=>{const session=sessionFor(req);if(!session){json(res,401,{error:'Nicht angemeldet.'});return null}return session};
const readManifest=async()=>JSON.parse(await readFile(manifestPath,'utf8'));
const titleFromMarkdown=(content,fallback)=>content.match(/^---[\r\n]+[\s\S]*?title:\s*["']?([^\r\n"']+)["']?[\r\n]+[\s\S]*?---/i)?.[1]?.trim()||fallback.replace(/\.md$/i,'').replace(/^\d{2}-/,'').replace(/[-_]+/g,' ');
const slug=value=>value.toLowerCase().replace(/\.md$/,'').replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'');
const scanMarkdown=async(dir,prefix='')=>{const entries=await readdir(dir,{withFileTypes:true}),result=[];for(const entry of entries.sort((a,b)=>a.name.localeCompare(b.name))){if(entry.name.startsWith('.')||entry.name==='manifest.json')continue;const relative=prefix?`${prefix}/${entry.name}`:entry.name;if(entry.isDirectory())result.push(...await scanMarkdown(join(dir,entry.name),relative));else if(entry.isFile()&&entry.name.endsWith('.md')){const content=await readFile(join(dir,entry.name),'utf8');result.push({id:slug(relative),path:relative,title:titleFromMarkdown(content,entry.name)})}}return result};
const syncManifest=async()=>{const manifest=await readManifest(),scanned=await scanMarkdown(docsPath),documents=scanned.map(doc=>({...doc,...(manifest.documents||[]).find(item=>item.path===doc.path)})),next={...manifest,content:{...(manifest.content||{}),format:'markdown',directory:'docs'},documents};await writeFile(manifestPath,JSON.stringify(next,null,2)+'\n');return next};
let manifestCache=await syncManifest();
const safeRelative=value=>{const normalized=normalize(String(value||'')).replace(/^([/\\])+/, '');if(!normalized||normalized.startsWith('..')||normalized.includes('\\')||normalized.includes('/')&&!normalized.split('/').every(p=>p!==''&&p!=='.'&&p!=='..'))return null;return normalized};
const safeNewPath=value=>{const normalized=safeRelative(value);if(!normalized||!normalized.endsWith('.md')||normalized==='manifest.json')return null;return join(docsPath,normalized)};
const safeManifestPath=relativePath=>{const normalized=safeRelative(relativePath);if(!normalized||!normalized.endsWith('.md'))return null;return manifestCache.documents?.some(d=>d.path===normalized)?join(docsPath,normalized):null};
const git=async args=>{const {stdout}=await execFileAsync('git',args,{cwd:root,timeout:15000,maxBuffer:500000});return stdout.trim()};
const checkCsrf=(req,csrf)=>{const session=sessionFor(req);return session&&same(session.csrf,String(csrf||''))};

createServer(async(req,res)=>{const url=new URL(req.url||'/',`http://${req.headers.host||'localhost'}`);try{
manifestCache=await syncManifest();
if(req.method==='POST'&&url.pathname==='/api/login'){const {password}=await body(req);if(typeof password!=='string'||!same(adminPassword,password))return json(res,401,{error:'Passwort stimmt nicht.'});const id=randomBytes(24).toString('hex'),csrf=randomBytes(24).toString('hex');sessions.set(id,{csrf});res.writeHead(200,{'Content-Type':'application/json; charset=utf-8','Set-Cookie':`blueprint_session=${id}; HttpOnly; SameSite=Strict; Path=/`});return res.end(JSON.stringify({csrf}))}
if(req.method==='POST'&&url.pathname==='/api/logout'){const id=/(?:^|; )blueprint_session=([^;]+)/.exec(req.headers.cookie||'')?.[1];if(id)sessions.delete(id);res.writeHead(204,{'Set-Cookie':'blueprint_session=; Max-Age=0; Path=/'});return res.end()}
if(req.method==='GET'&&url.pathname==='/api/content')return json(res,200,JSON.parse(await readFile(contentPath,'utf8')));
if(req.method==='GET'&&url.pathname==='/api/editor-content'){if(!requireAuth(req,res))return;return json(res,200,JSON.parse(await readFile(contentPath,'utf8')))}
if(req.method==='GET'&&url.pathname==='/api/docs'){if(!requireAuth(req,res))return;return json(res,200,manifestCache.documents||[])}
if(req.method==='POST'&&url.pathname==='/api/docs'){const session=requireAuth(req,res);if(!session)return;const data=await body(req);if(!checkCsrf(req,data.csrf))return json(res,403,{error:'Sitzung abgelaufen. Bitte neu anmelden.'});const filePath=safeNewPath(data.path);if(!filePath)return json(res,400,{error:'Ungültiger Markdown-Dateiname.'});if(typeof data.content!=='string'||data.content.length>100000)return json(res,422,{error:'Ungültiger Dokumentinhalt.'});try{await readFile(filePath);return json(res,409,{error:'Diese Datei existiert bereits.'})}catch(error){if(error.code!=='ENOENT')throw error}await mkdir(dirname(filePath),{recursive:true});await writeFile(filePath,data.content.endsWith('\n')?data.content:`${data.content}\n`);manifestCache=await syncManifest();return json(res,201,{ok:true,path:safeRelative(data.path)})}
if(req.method==='GET'&&url.pathname==='/api/git/status'){if(!requireAuth(req,res))return;const status=await git(['status','--short']),branch=await git(['branch','--show-current']),diff=await git(['diff','--','docs']);return json(res,200,{branch,status,diff,clean:!status})}
if(req.method==='POST'&&(url.pathname==='/api/git/commit'||url.pathname==='/api/git/push')){const session=requireAuth(req,res);if(!session)return;const {csrf,message}=await body(req);if(!checkCsrf(req,csrf))return json(res,403,{error:'Sitzung abgelaufen. Bitte neu anmelden.'});const commitMessage=typeof message==='string'?message.trim():'';if(commitMessage.length<3||commitMessage.length>120)return json(res,422,{error:'Commit-Nachricht muss 3–120 Zeichen lang sein.'});await git(['add','docs']);const staged=await git(['diff','--cached','--name-only']);if(!staged)return json(res,409,{error:'Keine Änderungen in docs zum Committen.'});await git(['commit','-m',commitMessage]);if(url.pathname==='/api/git/push')await git(['push','origin','main']);return json(res,200,{ok:true,pushed:url.pathname==='/api/git/push',commit:await git(['rev-parse','--short','HEAD'])})}
const docMatch=url.pathname.match(/^\/api\/docs\/(.+)$/);if(docMatch&&(req.method==='GET'||req.method==='POST'||req.method==='PATCH'||req.method==='DELETE')){const session=requireAuth(req,res);if(!session)return;const relativePath=decodeURIComponent(docMatch[1]),filePath=safeManifestPath(relativePath);if(!filePath)return json(res,400,{error:'Dokument ist nicht im Manifest freigegeben.'});if(req.method==='GET')return json(res,200,{path:relativePath,content:await readFile(filePath,'utf8')});const data=await body(req);if(!checkCsrf(req,data.csrf))return json(res,403,{error:'Sitzung abgelaufen. Bitte neu anmelden.'});if(req.method==='POST'){if(typeof data.content!=='string'||data.content.length>100000)return json(res,422,{error:'Ungültiger Dokumentinhalt.'});await writeFile(filePath,data.content.endsWith('\n')?data.content:`${data.content}\n`);return json(res,200,{ok:true,path:relativePath})}if(req.method==='PATCH'){const newPath=safeNewPath(data.path);if(!newPath)return json(res,400,{error:'Ungültiger neuer Dateiname.'});try{await readFile(newPath);return json(res,409,{error:'Die Zieldatei existiert bereits.'})}catch(error){if(error.code!=='ENOENT')throw error}await mkdir(dirname(newPath),{recursive:true});await rename(filePath,newPath);manifestCache=await syncManifest();return json(res,200,{ok:true,path:safeRelative(data.path)})}await unlink(filePath);manifestCache=await syncManifest();return json(res,200,{ok:true})}
if(req.method==='GET'&&url.pathname==='/api/memo'){const fileName=String(url.searchParams.get('file')||''),filePath=safeManifestPath(fileName);if(!filePath)return json(res,400,{error:'Ungültige Memo-Datei.'});try{const content=await readFile(filePath,'utf8');res.writeHead(200,{'Content-Type':'text/markdown; charset=utf-8','Cache-Control':'no-store'});return res.end(content)}catch{res.writeHead(404);return res.end('Not found')}}
if(req.method==='POST'&&url.pathname==='/api/content'){const session=requireAuth(req,res);if(!session)return;const {csrf,content}=await body(req);if(!checkCsrf(req,csrf))return json(res,403,{error:'Sitzung abgelaufen. Bitte neu anmelden.'});const existing=JSON.parse(await readFile(contentPath,'utf8'));if(!content||typeof content!=='object'||Object.keys(content).length!==Object.keys(existing).length||Object.keys(content).some(key=>!(key in existing)||typeof content[key]!=='string'||content[key].length>3000))return json(res,422,{error:'Ungültiger Inhalt.'});await writeFile(contentPath,JSON.stringify(Object.fromEntries(Object.keys(existing).map(key=>[key,content[key].trim()])),null,2)+'\n');return json(res,200,{ok:true})}
let requested=url.pathname==='/'?'index.html':url.pathname==='/admin/'?'admin.html':url.pathname.slice(1);requested=normalize(requested).replace(/^([/\\])+/, '');const file=join(root,requested);if(!file.startsWith(root)||requested.includes('private')||requested.startsWith('config')||requested.endsWith('.php')){res.writeHead(404);return res.end()}const fileData=await readFile(file);res.writeHead(200,{'Content-Type':mime[extname(file)]||'application/octet-stream'});res.end(fileData);
}catch(error){console.error(error);json(res,error.code==='ENOENT'?404:500,{error:error.code==='ENOENT'?'Nicht gefunden.':'Serverfehler.'})}}).listen(port,'127.0.0.1',()=>console.log(`Blueprint läuft auf http://127.0.0.1:${port}\nEditor: http://127.0.0.1:${port}/admin/`));
